---
title: "NYC Restaurant Inspections (April 19,2013 - October 16,2017)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(tidyverse)
library(dplyr)
library(p8105.datasets)
```

```{r dataset, include=FALSE}
data("rest_inspec")

rest_inspec = 
  rest_inspec %>% 
    as_tibble(rest_inspec) %>% 
      janitor::clean_names() %>% 
        select(boro, cuisine_description, inspection_date, violation_code, violation_description, 
               grade, score) %>% 
            filter(grade %in% c("A", "B", "C")) %>% 
             slice_sample(n=1000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Cuisine types across boroughs in NYC 

```{r}
rest_inspec %>% 
  group_by(boro) %>% 
  summarise(cuisine_description) %>% 
  count(cuisine_description) %>% 
  plot_ly(x= ~boro, y= ~n, color= ~cuisine_description, type= "bar") %>% 
  layout(title= "Restaurant Types in NYC Boroughs", xaxis= list(title= "Borough"), 
         yaxis= list(title="Number of Restaurant Type"))
  
```

Column {data-width=350}
-----------------------------------------------------------------------

### Food inspection scores across NYC boroughs 

```{r}
rest_inspec %>% 
  plot_ly(x = ~boro, y= ~score, type="box", color="viridis" ) %>% 
  
   layout(yaxis = list(categoryorder = "total descending")) %>% 
        layout(showlegend = FALSE,
              xaxis = list(title = "Borough", tickangle=45),
              yaxis = list(title = "Count"),
              title = "NYC Restaurant Inspection Scores across Boroughs")
```

### Recorded restaurant inspeciton violations 

```{r}
rest_inspec %>% 
  group_by(violation_code, violation_description) %>% 
  count(violation_code) %>% 
  mutate(violation_code = fct_reorder(violation_code, n)) %>% 
  
  plot_ly(x = ~n, y= ~violation_code, type = "bar",
          text= ~violation_description, 
          color= ~violation_code) %>% 
  
   layout(yaxis = list(categoryorder = "total descending")) %>% 
      add_bars(textposition = "none") %>% 
        layout(showlegend = FALSE,
           barmode = "stack",
              xaxis = list(title = "Violations", tickangle=45),
              yaxis = list(title = "Violation Code"),
              title = "Common NYC Restaurant Inspection Violations")
```

